#!/bin/bash
#SBATCH --job-name=k100-retr-bl
#SBATCH --output=outputs/k100_retrieval_baselines_%j.log
#SBATCH --error=outputs/k100_retrieval_baselines_%j.log
#SBATCH --partition=lambda
#SBATCH --gres=gpu:4
#SBATCH --cpus-per-task=64
#SBATCH --mem=200G
#SBATCH --time=24:00:00

# =============================================================================
# DPR + ColBERT baselines for NQ and HotpotQA k100
#
# Token-count matching (1 epoch):
#   HotpotQA: 50k × 2 gold × 25 negs = 2.5M triplets (~0.56B tokens)
#     → matches long-context 50k × ~11.7k tok/ex = 0.59B tokens
#   NQ: 48k × 1 gold × 40 negs = 1.9M triplets (~1.27B tokens)
#     → matches long-context 48k × ~25.8k tok/ex = 1.24B tokens
#
# Experiments:
#   1. DPR — HotpotQA
#   2. DPR — NQ
#   3. ColBERT — HotpotQA
#   4. ColBERT — NQ
#
# Monitor: tail -f outputs/k100_retrieval_baselines_<JOBID>.log
# =============================================================================

PROJECT_DIR="/accounts/projects/sewonm/prasann/projects/corpus-reasoning"
cd "$PROJECT_DIR"

eval "$(conda shell.bash hook)"
conda activate corpus-reasoning-retrieval

set -eo pipefail

# --- Triplet data paths (generated by run_k100_data_gen or inline) ---
HPQA_TRIPLETS="data/hotpotqa_train_triplets_bridge_neg25_500000.jsonl"
NQ_TRIPLETS="data/nq_train_triplets_neg40_400000.jsonl"

# --- Eval data ---
HPQA_EVAL="data/hotpotqa_eval_k100_shuffled_bridge_500.jsonl"
NQ_EVAL="data/nq_validation_k40_random_500.jsonl"

echo "=============================================="
echo "k100 Retrieval Baselines — DPR + ColBERT"
echo "Job ID: ${SLURM_JOB_ID:-local}"
echo "Started: $(date)"
echo "=============================================="

# --- Check triplet files exist ---
for f in "$HPQA_TRIPLETS" "$NQ_TRIPLETS"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: Triplet file not found: $f"
        echo "Generate with: python scripts/data/generate_retrieval_triplets.py ..."
        exit 1
    fi
done

# =============================================================================
# 1. DPR — HotpotQA
# =============================================================================
echo ""
echo "======================================================"
echo "[1/4] DPR — HotpotQA"
echo "Started: $(date)"
echo "======================================================"

torchrun --nproc_per_node=4 scripts/train/train_retrieval_baseline.py \
    --mode dpr \
    --train-data "$HPQA_TRIPLETS" \
    --eval-data "$HPQA_EVAL" \
    --model-name answerdotai/ModernBERT-base \
    --lr 3e-5 --epochs 1 --batch-size 256 --mini-batch-size 32 \
    --dataset-tag hotpotqa-k100

echo "--- DPR HotpotQA Eval ---"
HPQA_DPR_MODEL="outputs/ModernBERT-base-dpr-hotpotqa-k100/final"
python scripts/eval/evaluate_retrieval_baseline.py \
    --mode dpr \
    --model-path "$HPQA_DPR_MODEL" \
    --eval-data "$HPQA_EVAL" \
    --output-file "outputs/eval_dpr_hotpotqa_k100.json"

echo "[1/4] Done: $(date)"

# =============================================================================
# 2. DPR — NQ
# =============================================================================
echo ""
echo "======================================================"
echo "[2/4] DPR — NQ"
echo "Started: $(date)"
echo "======================================================"

torchrun --nproc_per_node=4 scripts/train/train_retrieval_baseline.py \
    --mode dpr \
    --train-data "$NQ_TRIPLETS" \
    --eval-data "$NQ_EVAL" \
    --model-name answerdotai/ModernBERT-base \
    --lr 3e-5 --epochs 1 --batch-size 256 --mini-batch-size 32 \
    --dataset-tag nq-k100

echo "--- DPR NQ Eval ---"
NQ_DPR_MODEL="outputs/ModernBERT-base-dpr-nq-k100/final"
python scripts/eval/evaluate_retrieval_baseline.py \
    --mode dpr \
    --model-path "$NQ_DPR_MODEL" \
    --eval-data "$NQ_EVAL" \
    --output-file "outputs/eval_dpr_nq_k100.json"

echo "[2/4] Done: $(date)"

# =============================================================================
# 3. ColBERT — HotpotQA
# =============================================================================
echo ""
echo "======================================================"
echo "[3/4] ColBERT — HotpotQA"
echo "Started: $(date)"
echo "======================================================"

torchrun --nproc_per_node=4 scripts/train/train_retrieval_baseline.py \
    --mode colbert \
    --train-data "$HPQA_TRIPLETS" \
    --eval-data "$HPQA_EVAL" \
    --model-name answerdotai/ModernBERT-base \
    --lr 3e-5 --epochs 1 --batch-size 256 --mini-batch-size 32 \
    --embedding-dim 128 \
    --dataset-tag hotpotqa-k100

echo "--- ColBERT HotpotQA Eval ---"
HPQA_COLBERT_MODEL="outputs/ModernBERT-base-colbert-hotpotqa-k100/final"
python scripts/eval/evaluate_retrieval_baseline.py \
    --mode colbert \
    --model-path "$HPQA_COLBERT_MODEL" \
    --eval-data "$HPQA_EVAL" \
    --output-file "outputs/eval_colbert_hotpotqa_k100.json"

echo "[3/4] Done: $(date)"

# =============================================================================
# 4. ColBERT — NQ
# =============================================================================
echo ""
echo "======================================================"
echo "[4/4] ColBERT — NQ"
echo "Started: $(date)"
echo "======================================================"

torchrun --nproc_per_node=4 scripts/train/train_retrieval_baseline.py \
    --mode colbert \
    --train-data "$NQ_TRIPLETS" \
    --eval-data "$NQ_EVAL" \
    --model-name answerdotai/ModernBERT-base \
    --lr 3e-5 --epochs 1 --batch-size 256 --mini-batch-size 32 \
    --embedding-dim 128 \
    --dataset-tag nq-k100

echo "--- ColBERT NQ Eval ---"
NQ_COLBERT_MODEL="outputs/ModernBERT-base-colbert-nq-k100/final"
python scripts/eval/evaluate_retrieval_baseline.py \
    --mode colbert \
    --model-path "$NQ_COLBERT_MODEL" \
    --eval-data "$NQ_EVAL" \
    --output-file "outputs/eval_colbert_nq_k100.json"

echo "[4/4] Done: $(date)"

echo ""
echo "=============================================="
echo "All retrieval baselines done: $(date)"
echo "=============================================="
