base_model: Qwen/Qwen3.5-0.8B-Base

datasets:
  - path: data/hotpotqa_train_k20_shuffled_retrieval_bridge_5000_ad100.jsonl
    type: alpaca
    ds_type: json

val_set_size: 0.0
output_dir: ./outputs/hotpotqa-k20-chunked-qbefore-qwen-lora-ad100

wandb_project: corpus-reasoning
wandb_name: chunked_qbefore_hotpotqa_k20_5k_qwen_lora_ad100

sequence_len: 8192
micro_batch_size: 1
gradient_accumulation_steps: 8
num_epochs: 1
learning_rate: 5e-4
sample_packing: false
eval_sample_packing: false
flash_attention: false
query_position: before
standard_attention: false
train_on_inputs: false

before_dummy: 0
after_dummy: 100

adapter: lora
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules: [gate_proj, down_proj, up_proj, q_proj, v_proj, k_proj, o_proj]
optimizer: adamw_8bit
lr_scheduler: cosine
bf16: auto
tf32: true
gradient_checkpointing: true
logging_steps: 1
saves_per_epoch: 0
save_strategy: 'no'
evals_per_epoch: 0
warmup_ratio: 0.1
weight_decay: 0.0
deepspeed: configs/deepspeed_zero1.json
special_tokens:
  pad_token: "<|endoftext|>"
