"""
Evaluate models on the contradiction detection task using vLLM.

Loads eval data generated by generate_contradiction_data.py and computes:
  - Pair-level precision, recall, F1 (did the model find the right pairs?)
  - Exact match (did the model get ALL pairs exactly right?)
  - Parse rate (fraction of outputs that are valid JSON)

Usage:
    python scripts/evaluate_contradiction.py --eval-data data/contradiction_eval_n20_k3.jsonl
    python scripts/evaluate_contradiction.py --eval-data data/contradiction_eval_n50_k5.jsonl --lora-path outputs/contradiction-lora
"""

import argparse
import json
import os
import re
from pathlib import Path

from vllm import LLM, SamplingParams
from vllm.lora.request import LoRARequest


def parse_pairs(text: str) -> list[list[int]] | None:
    """Try to parse a list of pairs from model output.

    Handles formats like:
      [[1, 4], [3, 7]]
      [[1,4],[3,7]]
      [1, 4], [3, 7]
      (1, 4), (3, 7)
    """
    text = text.strip()

    # Try direct JSON parse first
    try:
        parsed = json.loads(text)
        if isinstance(parsed, list):
            pairs = []
            for item in parsed:
                if isinstance(item, list) and len(item) == 2:
                    pairs.append(sorted([int(item[0]), int(item[1])]))
            return pairs
    except (json.JSONDecodeError, ValueError, TypeError):
        pass

    # Try to find JSON array in the text
    match = re.search(r'\[[\s\S]*\]', text)
    if match:
        try:
            parsed = json.loads(match.group())
            if isinstance(parsed, list):
                pairs = []
                for item in parsed:
                    if isinstance(item, list) and len(item) == 2:
                        pairs.append(sorted([int(item[0]), int(item[1])]))
                return pairs
        except (json.JSONDecodeError, ValueError, TypeError):
            pass

    # Try to extract individual pairs with regex
    pair_pattern = re.compile(r'[\[\(]\s*(\d+)\s*,\s*(\d+)\s*[\]\)]')
    matches = pair_pattern.findall(text)
    if matches:
        return [sorted([int(a), int(b)]) for a, b in matches]

    # Check for empty list
    if text.strip() in ("[]", ""):
        return []

    return None


def compute_pair_metrics(
    predicted_pairs: list[list[int]],
    gold_pairs: list[list[int]],
) -> dict:
    """Compute precision, recall, F1 at the pair level."""
    pred_set = {tuple(p) for p in predicted_pairs}
    gold_set = {tuple(p) for p in gold_pairs}

    if len(pred_set) == 0 and len(gold_set) == 0:
        return {"precision": 1.0, "recall": 1.0, "f1": 1.0, "exact_match": 1.0}

    true_pos = len(pred_set & gold_set)
    precision = true_pos / len(pred_set) if pred_set else 0.0
    recall = true_pos / len(gold_set) if gold_set else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    exact_match = 1.0 if pred_set == gold_set else 0.0

    return {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "exact_match": exact_match,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Evaluate contradiction detection with vLLM"
    )
    parser.add_argument("--base-model", type=str, default="NousResearch/Llama-3.2-1B")
    parser.add_argument("--lora-path", type=str, default="",
                        help="Path to LoRA adapter (empty to skip)")
    parser.add_argument("--eval-data", type=str, required=True,
                        help="Path to eval JSONL from generate_contradiction_data.py")
    parser.add_argument("--max-test-samples", type=int, default=200)
    parser.add_argument("--max-model-len", type=int, default=4096)
    parser.add_argument("--max-tokens", type=int, default=200,
                        help="Max new tokens for generation")
    parser.add_argument("--tensor-parallel-size", type=int, default=1)
    parser.add_argument("--output-file", type=str,
                        default="outputs/contradiction_eval_results.json")
    args = parser.parse_args()

    # Load eval data
    print(f"Loading eval data from {args.eval_data}...")
    examples = []
    with open(args.eval_data) as f:
        for line in f:
            examples.append(json.loads(line))

    if args.max_test_samples and len(examples) > args.max_test_samples:
        import random
        random.seed(42)
        examples = random.sample(examples, args.max_test_samples)

    print(f"  Loaded {len(examples)} examples")

    # Build prompts — using the alpaca-style format
    prompts = []
    gold_answers = []
    for ex in examples:
        # Reconstruct the prompt as the model would see it during training
        prompt = (
            f"Below is an instruction that describes a task, paired with an input "
            f"that provides further context. Write a response that appropriately "
            f"completes the request.\n\n"
            f"### Instruction:\n{ex['instruction']}\n\n"
            f"### Input:\n{ex['input']}\n\n"
            f"### Response:\n"
        )
        prompts.append(prompt)
        gold_answers.append(json.loads(ex["output"]))

    # Show prompt length stats
    prompt_lens = [len(p) for p in prompts]
    print(f"  Prompt length (chars): min={min(prompt_lens)}, max={max(prompt_lens)}, "
          f"avg={sum(prompt_lens)/len(prompt_lens):.0f}")

    # Load model
    enable_lora = bool(args.lora_path)
    print(f"\nLoading model: {args.base_model} (enable_lora={enable_lora})")
    llm = LLM(
        model=args.base_model,
        enable_lora=enable_lora,
        max_lora_rank=64 if enable_lora else None,
        tensor_parallel_size=args.tensor_parallel_size,
        max_model_len=args.max_model_len,
        gpu_memory_utilization=0.5,
    )

    sampling_params = SamplingParams(
        temperature=0.0,
        max_tokens=args.max_tokens,
    )

    lora_request = None
    if args.lora_path:
        lora_request = LoRARequest("lora", 1, str(Path(args.lora_path).resolve()))

    # Run inference
    model_tag = "lora" if lora_request else "base"
    print(f"\nRunning inference ({model_tag})...")
    outputs = llm.generate(prompts, sampling_params, lora_request=lora_request)
    responses = [o.outputs[0].text for o in outputs]

    # Evaluate
    results = []
    parse_failures = 0
    for i, (resp, gold) in enumerate(zip(responses, gold_answers)):
        predicted = parse_pairs(resp)
        if predicted is None:
            parse_failures += 1
            predicted = []

        metrics = compute_pair_metrics(predicted, gold)
        results.append({
            "gold_pairs": gold,
            "predicted_pairs": predicted,
            "raw_output": resp.strip()[:500],
            "parsed": predicted is not None,
            **metrics,
        })

    # Aggregate
    n = len(results)
    avg_metrics = {
        "precision": sum(r["precision"] for r in results) / n,
        "recall": sum(r["recall"] for r in results) / n,
        "f1": sum(r["f1"] for r in results) / n,
        "exact_match": sum(r["exact_match"] for r in results) / n,
        "parse_rate": (n - parse_failures) / n,
    }

    # Print results
    print(f"\n{'='*60}")
    print(f"Results ({model_tag}) — {len(results)} examples")
    print(f"{'='*60}")
    print(f"  Parse rate:       {avg_metrics['parse_rate']:.1%}")
    print(f"  Pair Precision:   {avg_metrics['precision']:.1%}")
    print(f"  Pair Recall:      {avg_metrics['recall']:.1%}")
    print(f"  Pair F1:          {avg_metrics['f1']:.1%}")
    print(f"  Exact Match:      {avg_metrics['exact_match']:.1%}")

    # Show sample predictions
    print(f"\n  Sample predictions:")
    for r in results[:5]:
        print(f"    Gold:      {r['gold_pairs']}")
        print(f"    Predicted: {r['predicted_pairs']}")
        print(f"    Output:    {r['raw_output'][:120]}")
        print(f"    EM={r['exact_match']:.0f} P={r['precision']:.2f} R={r['recall']:.2f} F1={r['f1']:.2f}")
        print()

    # Save results
    os.makedirs(os.path.dirname(args.output_file) or ".", exist_ok=True)
    output = {
        "args": vars(args),
        "summary": avg_metrics,
        "results": results,
    }
    with open(args.output_file, "w") as f:
        json.dump(output, f, indent=2)
    print(f"Results saved to {args.output_file}")


if __name__ == "__main__":
    main()
